server:
  port: 12000
spring:
  cloud:
    zookeeper:
      connect-string: 47.103.72.44:2181
      discovery:
        root: /oauth/jxw/service/@project.version@

logging:
  level: debug
  file:
    path: E:\\Cache\\Logs\\oauthZuul

#spring-sercurity-oauth 请求授权url
oauth:
  passwordAccessToken: http://localhost:12001/oauth/token?grant_type=password
  refreshAccessToken: http://localhost:12001/oauth/token?grant_type=refresh_token&refresh_token=
  codeAccessToken: http://localhost:12001/oauth/token?grant_type=authorization_code