server:
  port: 12001
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.22.230:5432/road_oauth
    username: postgres
    password: PGpwd+*8
    hikari:
      maximum-pool-size: 50
      auto-commit: false
      idle-timeout: 180000
      max-lifetime: 300000
      minimum-idle: 5
  redis:
    cluster:
      nodes:
        - 192.168.22.230:7000
        - 192.168.22.230:7001
        - 192.168.22.230:7002
  cloud:
    zookeeper:
      discovery:
        root: /authorityCenter/dev_gms/service/@project.version@
      connect-string:  192.168.22.230:2181



logging:
  level:
    com.vapor.repository: DEBUG
  path: /tmp/logs/authorityCenter/oauth2


#spring-sercurity-oauth 请求授权url
oauth:
  passwordAccessToken: http://localhost:12001/oauth/token?grant_type=password
  refreshAccessToken: http://localhost:12001/oauth/token?grant_type=refresh_token&refresh_token=
  codeAccessToken: http://localhost:12001/oauth/token?grant_type=authorization_code