feign:
  hystrix:
    enabled: false
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  before: true
  not-empty: false
mybatis:
  type-aliases-package: com.tingbei.common.entity
  mapper-locations: classpath*:mapper/**/*.xml
ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 60000

spring:
  application:
    name: oauth2Server
